# -*- coding: utf-8 -*-
"""calculadora funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRsH2cDZKBZWC2yrKVX0i5SMiOeJPaKG
"""

# Importando la libreria/biblioteca de matemáticas de Python:
import math

# DEFINICION DE LAS FUNCIONES:
def mostrar_titulo():
  '''
  input: no hay entradas
  process: mostrar titulo (está implícito en el nombre de la función, se sugiere que sea un verbo)
  output: no hay salidas
  '''
  print('Ejemplo Calculadora Sencilla (+,-,*,/, potencia, raiz, log, sin, cos, tan) por Julio T:')

def mostrar_menu():
  '''input: no recibe nada (0 entradas)
  process:mostrar menu
  output: no retorna nada (0 salidas)'''
  print()
  print("MENU:")
  print("1: Sumar (+)")
  print("2: Restar (-)")
  print("3: Multiplicar (*)")
  print("4: Dividir (/)")
  print("5: Potenciación (pow)")
  print("6: Radicación (sqrt)")
  print("7: Logaritmo (log10)")
  print("8: Seno (sin)")
  print("9: Coseno (cos)")
  print("10: Tangente (tan)")
  print()

def ingresar_datos():
  '''input: no hay entradas
  process:ingresar datos (recibir/leer del usuario)
  output: tres variables que contienen localmente las decisiones del usuario (opcion,numero_uno,numero_dos)'''
  opcion=input("Ingrese la opción deseada del menú: ") # la opción se guarda como cadena
  numero_uno=float(input('Ingrese el primer número de la operación:'))# guarda como flotante (número real)
  numero_dos=float(input('Ingrese el segundo número de la operación:'))# guarda como flotante (número real)
  return opcion,numero_uno,numero_dos

# POR FACILIDAD, LAS 10 FUNCIONES SIGUIENTES TIENEN ENTRADAS Y SALIDAS
def calcular_suma(numero_uno,numero_dos):
  '''input: 2 numeros
  process:calcular suma (sumar)
  output: suma'''
  suma=numero_uno+numero_dos
  return suma

def calcular_resta(numero_uno,numero_dos):
  return numero_uno-numero_dos

def calcular_multiplicacion(numero_uno,numero_dos):
  return numero_uno*numero_dos

def calcular_division(numero_uno,numero_dos):
  return numero_uno/numero_dos

def calcular_potenciacion(base, exponente):
  return base**exponente

def calcular_radicacion(numero):
  return math.sqrt(numero)

def calcular_logaritmo_base10(numero):#x=numero (uno,dos)
  #aquí uso la función logaritmo que está dentro de math
  logaritmo=math.log10(numero)#x=numero
  return logaritmo

def calcular_seno(angulo_radianes):
  return math.sin(angulo_radianes)

def calcular_coseno(angulo_radianes):#x=numero (uno,dos): se debe asociar con un angulo que se toma por defecto en radianes (Si está en grados, debe convertirse a radianes=angulo*3.1416/180)
  #aquí uso la función coseno que está dentro de math
  coseno=math.cos(angulo_radianes)#x=numero (angulo_radianes)
  return coseno

def calcular_tangente(angulo_radianes):
  return math.tan(angulo_radianes)

def procesar_y_mostrar_operacion(opcion,numero_uno,numero_dos):
  '''input: opcion, numero_uno, numero_dos
  process:procesar y mostrar operacion (analizar las posibilidades para ejecutar la calculadora)
  output: no retorna valor porque por dentro imprime por pantalla todo'''
  if opcion=='1' or opcion=='+' or opcion=='Sumar':
    print("Vamos a sumar(+) los dos valores ingresados:")
    resultado=calcular_suma(numero_uno,numero_dos)
    print('La suma es:',resultado)
  elif opcion=='2'or opcion=='-' or opcion=='Restar':
    print("Vamos a restar(-) los dos valores ingresados:\n")
    resultado=calcular_resta(numero_uno,numero_dos)
    print("Resultado=",resultado)
  elif opcion=='3'or opcion=='*' or opcion=='Multiplicar':
    print("Vamos a multiplicar(*) los dos valores ingresados:\n")
    resultado=calcular_multiplicacion(numero_uno,numero_dos)
    print("Resultado=",resultado)
  elif opcion=='4'or opcion=='/' or opcion=='Dividir':
    print("Vamos a dividir(/) los dos valores ingresados:\n")
    #VALIDANDO EL DENOMINADOR (debe ser diferente de cero)
    if numero_dos!=0:
      resultado=calcular_division(numero_uno,numero_dos)
      print("Resultado=",resultado)
    else:
      print("¡No es posible dividir entre cero!")
  elif opcion=='5' or opcion=='pow' or opcion=='Potenciacion':
    print("Vamos a calcular la potenciación de los valores ingresados:\n")
    resultado = calcular_potenciacion(numero_uno, numero_dos)
    print(f"{numero_uno} elevado a la {numero_dos} es: {resultado}")
  elif opcion=='6' or opcion=='sqrt' or opcion=='Radicacion':
    print("Vamos a calcular la raíz cuadrada de los valores ingresados:\n")
    resultado1 = calcular_radicacion(numero_uno)
    resultado2 = calcular_radicacion(numero_dos)
    print(f"La raíz cuadrada de {numero_uno} es: {resultado1}")
    print(f"La raíz cuadrada de {numero_dos} es: {resultado2}")
  elif opcion=='7'or opcion=='log10' or opcion=='Logaritmo':
    print("Vamos a calcular el logaritmo (log10) de los dos valores ingresados:\n")
    resultado1=calcular_logaritmo_base10(numero_uno)
    resultado2=calcular_logaritmo_base10(numero_dos)
    print("Resultado1=",resultado1)
    print("Resultado2=",resultado2)
  elif opcion=='8' or opcion=='sin' or opcion=='Seno':
    print("Vamos a calcular el seno de los dos valores ingresados (en radianes):\n")
    resultado1 = calcular_seno(numero_uno)
    resultado2 = calcular_seno(numero_dos)
    print(f"Seno de {numero_uno} es: {resultado1}")
    print(f"Seno de {numero_dos} es: {resultado2}")
  elif opcion=='9'or opcion=='cos' or opcion=='Coseno':
    print("Vamos a calcular el coseno (cos) de los dos valores ingresados (en radianes):\n")
    resultado1=calcular_coseno(numero_uno)
    resultado2=calcular_coseno(numero_dos)
    print("Resultado1=",resultado1)
    print("Resultado2=",resultado2)
  elif opcion=='10' or opcion=='tan' or opcion=='Tangente':
    print("Vamos a calcular la tangente de los dos valores ingresados (en radianes):\n")
    resultado1 = calcular_tangente(numero_uno)
    resultado2 = calcular_tangente(numero_dos)
    print(f"Tangente de {numero_uno} es: {resultado1}")
    print(f"Tangente de {numero_dos} es: {resultado2}")
  else:
    print("Opción no válida. Por favor, intente de nuevo.")

def llamar_funciones():
  '''input: no hay entradas
  process:llamar funciones (en orden: mostrar_titulo,mostrar_menu, ingresar_datos, procesar_y_mostrar_operacion)
  output: no hay salidas'''
  mostrar_titulo()
  mostrar_menu()
  opcion,numero_uno,numero_dos=ingresar_datos()
  procesar_y_mostrar_operacion(opcion,numero_uno,numero_dos)

llamar_funciones()